"""
AI usage metering — the credit gate (completes Phase 9.4/9.5).

This deliberately reuses the schema migration 009 already shipped rather than
inventing a new one:
  - `users.ai_credits` (migration 007) is the spendable balance. It already
    defaults to 100 on signup, and admins can already top it up manually via
    POST /api/admin/users/{id}/credits (admin_console — unchanged here).
  - `usage_events` (migration 009) is the append-only audit ledger. It was
    defined but nothing ever wrote to it before this module existed.

Policy (matches the v1 decision already recorded in PHASE_9_PLAN.md and
PROJECT_MEMORY.md): one successful external AI reply or content generation
consumes exactly one credit; failures and local/offline fallbacks consume
nothing, because no Gemini call actually happened for those.

Fail-closed, like every other gate in this codebase (entitlements, tenant KB
search): a lookup error means "no credits", never "unlimited credits". A
credit *debit* failure, by contrast, must never raise — by the time
`record_usage` runs, the Gemini call already happened and the reply may
already be on its way to the customer; a bookkeeping hiccup cannot be allowed
to break that response (same contract as notification_service.create).
"""
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, Optional

from src.core.logger import logger
from src.core.supabase_client import supabase_db

# Kind values match the names already used in PHASE_9_PLAN.md so the ledger
# lines up with the product doc instead of inventing new vocabulary.
KIND_AI_REPLY = "ai_reply"        # one inbox auto-reply generated by Gemini
KIND_AI_GENERATE = "ai_generate"  # one Content Studio post/reel/story generated by Gemini
KIND_KB_EMBED = "kb_embed"        # embedding generation for knowledge base document chunks
KIND_KB_VISION = "kb_vision"      # Gemini multimodal vision analysis for uploaded images

# Starting defaults for auto-grants — admin-adjustable in spirit (same as
# MULTI_PLATFORM_DISCOUNTS in services.py): a coded fallback, not a price.
# Tune these once real usage volume is observed; nothing else depends on the
# exact numbers.
CREDITS_PER_PLATFORM = 500
TRIAL_MINIMUM_CREDITS = 100  # matches the schema's own signup default


class UsageService:
    """Reads/debits the ai_credits balance and logs to usage_events."""

    # ---- Gate ---------------------------------------------------------
    def has_credits(self, user_id: str, amount: int = 1) -> bool:
        """True only if the balance can cover `amount`. Fails closed."""
        if not user_id:
            return False
        try:
            rows = supabase_db.select("users", {"id": user_id}) or []
            if not rows:
                from src.core.auth import user_store
                u = user_store.get_by_id(user_id)
                if u:
                    return int(u.get("ai_credits", 0) or 0) >= amount
                return False
            return int(rows[0].get("ai_credits", 0) or 0) >= amount
        except Exception as e:
            logger.warning(f"credit check failed for {user_id}: {e}")
            return False

    def balance(self, user_id: str) -> int:
        try:
            rows = supabase_db.select("users", {"id": user_id}) or []
            if rows:
                return int(rows[0].get("ai_credits", 0) or 0)
            from src.core.auth import user_store
            u = user_store.get_by_id(user_id)
            return int(u.get("ai_credits", 0) or 0) if u else 0
        except Exception as e:
            logger.warning(f"balance lookup failed for {user_id}: {e}")
            return 0

    # ---- Consumption ----------------------------------------------------
    def record_usage(self, user_id: str, kind: str, amount: int = 1,
                      meta: Optional[Dict[str, Any]] = None) -> None:
        """Logs one usage_events row and debits the balance. Never raises."""
        try:
            supabase_db.insert("usage_events", {
                "user_id": user_id, "kind": kind, "amount": amount, "meta": meta or {},
            })
        except Exception as e:
            logger.error(f"usage_events insert failed ({kind}) for {user_id}: {e}")
        try:
            rows = supabase_db.select("users", {"id": user_id}) or []
            if rows:
                current = int(rows[0].get("ai_credits", 0) or 0)
                supabase_db.update("users", user_id, {"ai_credits": max(0, current - amount)})
            else:
                from src.core.auth import user_store
                u = user_store.get_by_id(user_id)
                if u:
                    current = int(u.get("ai_credits", 0) or 0)
                    u["ai_credits"] = max(0, current - amount)
        except Exception as e:
            logger.error(f"ai_credits debit failed for {user_id}: {e}")
    # ---- Grants -----------------------------------------------------------
    def ensure_minimum_credits(self, user_id: str, minimum: int) -> None:
        """Tops the balance up to `minimum` only if it is currently lower.

        Never lowers an existing higher balance (e.g. a prior admin bonus).
        Idempotent by construction, unlike a blind '+= amount' grant — safe
        to call from a webhook a gateway might redeliver, or from a checkout
        path that might race the webhook for the same event.
        """
        try:
            rows = supabase_db.select("users", {"id": user_id}) or []
            if not rows:
                return
            current = int(rows[0].get("ai_credits", 0) or 0)
            if current < minimum:
                supabase_db.update("users", user_id, {"ai_credits": minimum})
                logger.info(f"ai_credits topped up for {user_id}: {current} -> {minimum}")
        except Exception as e:
            logger.error(f"ai_credits top-up failed for {user_id}: {e}")

    def grant_platform_credits(self, user_id: str, platform_count: int) -> None:
        """Called on paid subscription activation (billing/__init__.py webhook)."""
        self.ensure_minimum_credits(user_id, CREDITS_PER_PLATFORM * max(1, platform_count))

    def grant_trial_credits(self, user_id: str) -> None:
        """Called from EntitlementService.start_trial (services.py)."""
        self.ensure_minimum_credits(user_id, TRIAL_MINIMUM_CREDITS)

    # ---- Reporting ----------------------------------------------------
    def summary(self, user_id: str, days: int = 30) -> Dict[str, Any]:
        """Balance plus a lightweight recent breakdown, for the account page.

        v1 simplification: the shared `select` helper only does equality
        filters, so this scans the user's own usage_events in Python rather
        than filtering by date server-side. Fine at pre-launch volume;
        revisit with a windowed RPC if a single tenant's event count grows
        large enough for that to matter.
        """
        by_kind: Dict[str, int] = {}
        total = 0
        since = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()
        try:
            events = supabase_db.select("usage_events", {"user_id": user_id}) or []
            for e in events:
                if str(e.get("created_at") or "") < since:
                    continue
                amount = int(e.get("amount") or 0)
                kind = e.get("kind") or "other"
                by_kind[kind] = by_kind.get(kind, 0) + amount
                total += amount
        except Exception as e:
            logger.warning(f"usage summary failed for {user_id}: {e}")
        return {
            "ai_credits": self.balance(user_id),
            "used_last_30d": total,
            "by_kind": by_kind,
            "period_days": days,
        }

    # ---- Notice -------------------------------------------------------
    def notify_if_exhausted(self, user_id: str) -> None:
        """Best-effort 'you are out of credits' notice, throttled to once
        per 6-hour window so a burst of inbound messages while blocked
        cannot flood the notification bell."""
        try:
            from src.modules.notifications.service import notification_service
            recent = supabase_db.select("notifications", {"user_id": user_id}) or []
            cutoff = (datetime.now(timezone.utc) - timedelta(hours=6)).isoformat()
            for n in recent:
                meta = n.get("meta") or {}
                if meta.get("job") == "credits_exhausted" and str(n.get("created_at") or "") >= cutoff:
                    return
            notification_service.create(
                user_id, "⚠️ رصيد الردود الآلية خلص",
                "الوكيل الذكي أوقف الردود التلقائية مؤقتاً لأن رصيد الـ AI credits "
                "انتهى. الرسائل الجديدة لسه بتوصل لصندوق الوارد للرد اليدوي. "
                "اشحن الرصيد من لوحة الإدارة للاستمرار.",
                "warning", {"job": "credits_exhausted"},
            )
        except Exception as e:
            logger.warning(f"credit-exhausted notice skipped for {user_id}: {e}")


usage_service = UsageService()
